# Generated by Django 4.2 on 2023-04-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corona_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corona_prod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Age_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('exp_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('Strip_contain', models.IntegerField(blank=True, null=True)),
                ('usage', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('advertisable', models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='adv_related', to='api.advertisable')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_related', to='api.brand')),
                ('compositions', models.ManyToManyField(related_name='comp_related', to='api.compositions')),
                ('corona_prod', models.ForeignKey(default=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='corona_related', to='api.corona_prod')),
                ('prod_age_cat', models.ManyToManyField(related_name='prod_age_related', to='api.prod_age_cat')),
                ('prod_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_type_related', to='api.prod_type')),
            ],
        ),
    ]
