# Generated by Django 4.2 on 2023-04-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_information',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='Images'),
        ),
    ]
