# Generated by Django 4.2 on 2023-06-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Usage_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_cat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_information',
            name='prod_usage_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prod_usage_cat'),
        ),
    ]
