# Generated by Django 4.2 on 2023-06-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prod_usage_cat_product_information_prod_usage_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_age_cat',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='prod_usage_cat',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='prod_usage_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prod_usage_cat', verbose_name='Usage Category'),
        ),
    ]
