# Generated by Django 4.2 on 2023-09-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prod_age_cat_image_prod_usage_cat_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to='Images')),
            ],
        ),
        migrations.AddField(
            model_name='product_information',
            name='brand_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_typr_related', to='api.brand_type'),
        ),
    ]
