# Generated by Django 4.2 on 2023-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_brand_type_product_information_brand_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_information',
            name='image',
        ),
        migrations.AddField(
            model_name='product_information',
            name='info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
