# Generated by Django 4.2 on 2023-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_information_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_information',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
