# Generated by Django 4.2 on 2023-10-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_information_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_information',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_information',
            name='usage',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
