# Generated by Django 4.2 on 2023-10-09 02:59

import ImageUploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=250, upload_to=ImageUploader.models.PrescriptionImage.nameFile)),
            ],
        ),
    ]
