# Generated by Django 4.2 on 2023-09-23 03:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('payment_transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('ordered_item_cat', models.CharField(default='Medicine', max_length=50)),
                ('ordered_item_quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('cart', models.JSONField(null=True)),
                ('address', models.CharField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('delivery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delivery_status', verbose_name='Delivery Status')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment_type', verbose_name='Payment Type')),
            ],
        ),
    ]
