# Generated by Django 4.2 on 2023-07-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Detils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('payment_transaction_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('ordered_item_cat', models.CharField(default='Medicine', max_length=50)),
                ('ordered_item_quantity', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('cart', models.JSONField(null=True)),
                ('delivery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentDetails.delivery_status', verbose_name='Delivery Status')),
            ],
        ),
    ]
