# Generated by Django 4.2 on 2023-07-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_detils',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
