# Generated by Django 4.2 on 2023-07-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentDetails', '0003_alter_payment_detils_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_detils',
            name='order_id',
        ),
    ]
