# Generated by Django 4.2 on 2023-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentDetails', '0004_remove_payment_detils_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_detils',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment_detils',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
